# NumPy
* векторы и матрицы
Note:
* pip install numpy

In [2]:
import numpy as np # алиас - короткое наименование

In [3]:
np.__version__

'1.22.4'

## Вектор

Вектор - это набор данных, записанных в определенном порядке, либо в виде строки, либо столбика

In [4]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])

In [5]:
a.dtype

dtype('int32')

In [6]:
c = np.array([1, 2, 3, 4], dtype=float)
c.dtype

dtype('float64')

In [7]:
a + b

array([15, 23, 14,  8])

In [8]:
a * 2

array([20, 16, 10,  2])

## Матрица

In [9]:
m = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
m

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
m.shape # можно узнать размерность матрицы

(4, 3)

In [11]:
print(f"{m[0,0] = }")
print(f"{m[1,2] = }")
print(f"{m[-1,-1] = }")

m[0,0] = 1
m[1,2] = 6
m[-1,-1] = 12


In [12]:
m1 = np.matrix("1,2;3,4;5,6") # можно создать матрицу более короткой строкой
m1

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [13]:
m2 = np.matrix("-1,-3;9,7;-5,0")
m2

matrix([[-1, -3],
        [ 9,  7],
        [-5,  0]])

In [14]:
m1 + m2

matrix([[ 0, -1],
        [12, 11],
        [ 0,  6]])

In [15]:
m1 * 5

matrix([[ 5, 10],
        [15, 20],
        [25, 30]])

In [16]:
# Транспонирование матриц
m1.T

matrix([[1, 3, 5],
        [2, 4, 6]])

## Операции с векторами

In [17]:
arr = np.array([1,2,3,4])

In [18]:
# (1) 
arr_sum = 0
for i in range(len(arr)):
    arr_sum = arr_sum + arr[i]
print(arr_sum)

10


In [19]:
# (2) 
arr_sum = 0
for value in arr:
    arr_sum += value
print(arr_sum)

10


In [20]:
# (3) 
arr_sum = np.sum(arr)
print(arr_sum)

10


In [21]:
arr = np.array([1,-2,3,-4])
print(f"{np.sum(arr) = }")
print(f"{np.abs(arr) = }")

np.sum(arr) = -2
np.abs(arr) = array([1, 2, 3, 4])


In [22]:
a = [x for x in range(1,10)]
b = [x**2 for x in range(1,10)]
c = [x**3 for x in range(1,10)]
np.array([a,b,c])

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81],
       [  1,   8,  27,  64, 125, 216, 343, 512, 729]])

## Индексы

In [24]:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
a[1] = -1
a[-1] = -9
a

array([10, -1, 12, 13, 14, 15, 16, 17, 18, -9])

## Срезы

In [26]:
a = np.arange(10,20)
print(a)
print(a[1:4])
print(a[::2])
print(a[::-1])

[10 11 12 13 14 15 16 17 18 19]
[11 12 13]
[10 12 14 16 18]
[19 18 17 16 15 14 13 12 11 10]


In [27]:
a = np.arange(10,20)
b = a[1:4]
b[1] = -1
print(a)
print(b)

[10 11 -1 13 14 15 16 17 18 19]
[11 -1 13]


In [28]:
a = np.arange(10,20)
a[3:7] = 0
print(a)
a[::2] = -1
print(a)

[10 11 12  0  0  0  0 17 18 19]
[-1 11 -1  0 -1  0 -1 17 -1 19]


## Списочная индексация

In [29]:
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [30]:
b = a[[1,2,-1]] #копия
print(b)
b[0] = 100
print(a)
print(b)

[11 12 19]
[10 11 12 13 14 15 16 17 18 19]
[100  12  19]


In [31]:
a > 13

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [32]:
a[np.logical_and(a >=12, a<=18)]

array([12, 13, 14, 15, 16, 17, 18])

In [33]:
flags = a > 13
a[flags]

array([14, 15, 16, 17, 18, 19])

In [35]:
print(a)
a[a > 13] = -1
print (a)
a[[1,3,6]] = 0
print(a)

[10 11 12 13 -1 -1 -1 -1 -1 -1]
[10 11 12 13 -1 -1 -1 -1 -1 -1]
[10  0 12  0 -1 -1  0 -1 -1 -1]


## Индексы в многомерных массивах

In [36]:
m = np.arange(3 * 2 * 4).reshape(3,2,4) # 3 матрицы, 2 строчки, 4 столбца
m

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
m[1]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
m[1,1]

array([12, 13, 14, 15])

In [39]:
m[1,1,1]

13

In [40]:
m[1:]

array([[[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [41]:
m[:-1] # все кроме последней матрицы

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [43]:
m[:,0,:] # запятыми отделяем то, что нас интересует (первая строка каждой матрицы в данном случае)

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [44]:
m[:,-0,-1:]

array([[ 3],
       [11],
       [19]])

## Списочная индексация в многомерных массивах

In [46]:
m = np.arange(3 * 3).reshape(3,3) # 3 строчки, 3 столбца (1 матрица)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
m[[1,0,-1]]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [48]:
indexes = np.array([
    [0,1],
    [-1,-2]
])
m[indexes]

array([[[0, 1, 2],
        [3, 4, 5]],

       [[6, 7, 8],
        [3, 4, 5]]])

In [50]:
m[1] = [9,8,7]
m

array([[0, 1, 2],
       [9, 8, 7],
       [6, 7, 8]])

In [51]:
m[2] += 100
m

array([[  0,   1,   2],
       [  9,   8,   7],
       [106, 107, 108]])

In [52]:
m[:,-1:] += 10000
m

array([[    0,     1, 10002],
       [    9,     8, 10007],
       [  106,   107, 10108]])