# Случайные числа в NumPy

In [2]:
import numpy as np

## Случайные целые числа

In [9]:
# Вернуть случайное число в интервале [0;5)
np.random.randint(5)

4

In [10]:
np.random.randint(1, 10)

2

In [11]:
a = np.random.randint(1, 10)
type(a)

int

In [12]:
a = np.random.randint(1, 10, dtype=np.int32)
type(a)

numpy.int32

In [14]:
np.random.randint(1, 10, 5) # 5 чисел от 1 до 10
# в результате значения не уникальны

array([8, 5, 1, 4, 9])

In [15]:
np.random.randint(1, 10, (2,3,4))

array([[[6, 3, 4, 7],
        [1, 4, 5, 6],
        [5, 7, 4, 1]],

       [[2, 2, 9, 2],
        [3, 5, 9, 4],
        [4, 4, 3, 6]]])

In [16]:
np.random.randint(1, 10, size = (4,4))

array([[3, 4, 4, 3],
       [5, 2, 6, 5],
       [8, 1, 5, 1],
       [6, 2, 8, 2]])

In [19]:
np.random.choice(10, 5, replace=False) # почти аналог randint, но теперь значения уникальны

array([7, 4, 8, 5, 2])

In [22]:
a = np.arange(10)
np.random.choice(a, 5)

[0 1 2 3 4 5 6 7 8 9]


array([8, 0, 1, 2, 6])

In [23]:
np.random.choice([-1,0, 1], 5)

array([ 1,  1,  1, -1, -1])

In [24]:
np.random.choice(['Нет', 'Отмена', 'Да'], 5)

array(['Нет', 'Да', 'Нет', 'Да', 'Отмена'], dtype='<U6')

In [27]:
weather = ['Солнечно', 'Пасмурно', 'Дождливо', 'Ветренно']
perm = [0.1, 0.5, 0.3, 0.1]
np.random.choice(weather, size=7, p= perm)

array(['Пасмурно', 'Солнечно', 'Пасмурно', 'Пасмурно', 'Солнечно',
       'Дождливо', 'Дождливо'], dtype='<U8')

## Случайные дробные числа

In [28]:
np.random.rand(5)

array([0.39289125, 0.38678245, 0.43195975, 0.01231517, 0.83702688])

In [29]:
np.random.rand(2,3)

array([[0.9958137 , 0.81916906, 0.53607964],
       [0.96319419, 0.94362804, 0.61035673]])

In [31]:
# Случайные дробные числа в интервале
np.random.uniform(1, 10, 5)

array([1.12306472, 9.36691091, 4.75436918, 3.92521255, 8.13779854])

In [32]:
np.random.uniform(1, 10, (2,3))

array([[3.04313634, 3.28711862, 3.4030938 ],
       [8.19515174, 2.73423962, 9.97913159]])

In [35]:
a = list(range(10))
print(a)
np.random.shuffle(a) # перемешивание
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[4, 2, 0, 3, 5, 7, 6, 8, 1, 9]


In [39]:
cities = "Москва, Воронеж, Тула, Севастополь".split(', ')
np.random.shuffle(cities)
cities

['Севастополь', 'Воронеж', 'Тула', 'Москва']

# Ещё

In [40]:
np.random.bytes(20)

b'\x89\x8f_\x9c\xf9\x04I\xfc\x93\x9e\xd2\xc5\xebdL\xf2\xf0B\xbbo'

In [42]:
a = np.random.permutation(10)
a

array([8, 0, 6, 1, 9, 7, 3, 4, 5, 2])

In [44]:
a = np.random.rand(7,10)
a

array([[0.54423183, 0.71583066, 0.20691866, 0.45852017, 0.40245148,
        0.89190723, 0.01768951, 0.93258436, 0.65065709, 0.54233174],
       [0.11127654, 0.18879452, 0.77324562, 0.3047006 , 0.93247001,
        0.45522379, 0.85291656, 0.36120389, 0.34027691, 0.05698576],
       [0.27117089, 0.20349124, 0.97932965, 0.51303058, 0.57057098,
        0.62767737, 0.6865794 , 0.75919487, 0.90153327, 0.72296983],
       [0.85065659, 0.48842196, 0.2762709 , 0.44266028, 0.37772816,
        0.98018169, 0.09486756, 0.18075545, 0.58379886, 0.22448543],
       [0.23764694, 0.78722327, 0.21244008, 0.50100271, 0.85966775,
        0.80770015, 0.77793739, 0.69099308, 0.60117129, 0.20977808],
       [0.24309572, 0.30786392, 0.5233349 , 0.27549412, 0.79842599,
        0.787004  , 0.80503273, 0.13563677, 0.51345167, 0.50697794],
       [0.46516314, 0.70153893, 0.27844661, 0.89966168, 0.86364121,
        0.61609605, 0.2153374 , 0.15853777, 0.83163749, 0.02019359]])

In [46]:
a = np.where( a > 0.3, 1, 0)
a

array([[1, 1, 0, 1, 1, 1, 0, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 0, 1, 0],
       [0, 1, 0, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 0, 1, 0]])