HW:  Создать матрицу, заполнить случайными значениями, например от 10 до 99,
распечатать её и затем в цикле выбирать действия над матрицей, например: повернуть по часовой стрелке, повернуть против часовой стрелки, отразить по вертикали и тп. и и напечатать результат.


In [26]:
import numpy as np

row = int(input("Введите кол-во строк: "))
col = int(input("Введите кол-во столбцов: "))
m = np.random.randint(10, 99, size=(row,col))
print(m)

while 10 > 1:
   a = int(input("Введите номер действия:  \n  1 - повернуть по часовой стрелке,  \n 2 - повернуть против часовой стрелки,")) 
   if a == 1:
      m = np.rot90(m, k = 1, axes = (1,0)) # поворот по часовой стрелке
      print(m) 
   elif a == 2:
      m = np.rot90(m, k = 1, axes = (0,1)) # поворот против часовой стрелки
      print(m)
   elif a == 3:
      #m = np.lib.pad(m,((2,0)),'reflect') # можно сделать с помощью reflect  или через np.vsplit
      #m = np.vsplit(m, 2)
      
      print(m[::-1]) # кортеж
   elif a == 4:
      # можно сделать с помощью reflect  или через np.hsplit
      print(m[:0:-1])
   elif a == 5:
      break




[[95 71 13 18 58]
 [24 79 20 50 75]
 [82 96 79 44 27]
 [12 60 19 31 19]]
[[12 82 24 95]
 [60 96 79 71]
 [19 79 20 13]
 [31 44 50 18]
 [19 27 75 58]]
[[95 71 13 18 58]
 [24 79 20 50 75]
 [82 96 79 44 27]
 [12 60 19 31 19]]
[[12 60 19 31 19]
 [82 96 79 44 27]
 [24 79 20 50 75]
 [95 71 13 18 58]]
